{
 "title": "TechChallenge",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Quantidade Containers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_memory_usage_bytes{pod=~\"tech-api.*\", container!=\"POD\", container!=\"\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Uso CPU (node)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 14, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * sum by (node) (\n  rate(container_cpu_usage_seconds_total{container!=\"\", container!=\"POD\"}[5m])\n)\n/\nsum by (node) (\n  machine_cpu_cores\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "HPA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Target",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "avg(\n  100 * rate(container_cpu_usage_seconds_total{\n    namespace=\"techchallenge\",\n    pod=~\"tech-api.*\",\n    container!=\"\",\n    container!=\"POD\"\n  }[1m])\n  /\n  on(pod, namespace, container)\n  group_left\n  kube_pod_container_resource_requests{\n    namespace=\"techchallenge\",\n    pod=~\"tech-api.*\",\n    resource=\"cpu\",\n    unit=\"core\"\n  }\n)\n",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "MinPods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "1", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Max Pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 11, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "5", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Replicas",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=\"tech-api\", namespace=\"techchallenge\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Média", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Uso CPU (pod)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\"tech-api.*\", container!=\"POD\", container!=\"\"}[5m]) * 1000",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Uso memória (pod)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{pod=~\"tech-api.*\", container!=\"POD\", container!=\"\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Média requisições por status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_server_requests_seconds_count{pod=~\"tech-api.*\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Média Erro 429",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 22 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{status=\"429\"}[1m])",
     "legendFormat": "{{container}}"
    }
   ]
  }
 ]
}