version: "3.8"

services:
  db:
    image: mysql:8.0
    container_name: mysql-techchallenge
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: techchallange_db
    ports:
       - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ../scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    container_name: techchallenge-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/techchallange_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
