name: Java CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build do projeto
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Compilar projeto
        run: mvn clean install -DskipTests=true

  unit-tests:
    name: Testes unitários
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Rodar testes
        run: mvn test
